import { LitElement, html, nothing } from 'lit';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import { marked } from 'marked';
import { CHALLENGES, DOCUMENTS, QUESTIONS, TRACKS, type DocItem, type TypeChallenge } from './academy-content.js';
import { TYPE_SCRIPT_VERSIONS, VERSION_ERAS, type TypeScriptVersion, type VersionEra } from './version-history.js';
import '../components/academy-badge.js';
import '../academy.css';
import './version-history.css';

type Page='dashboard'|'curriculum'|'documentation'|'versions'|'challenges'|'assessments'|'case-study';
const progressKey='typescript-academy.progress';
const challengeKey='typescript-academy.challenges';

export class TypeScriptAcademy extends LitElement {
  static override properties={page:{state:true},menuOpen:{state:true},theme:{state:true},completed:{state:true},selectedDoc:{state:true},docHtml:{state:true},selectedChallenge:{state:true},draft:{state:true},challengeResult:{state:true},questionIndex:{state:true},answers:{state:true},assessmentDone:{state:true},selectedVersion:{state:true},versionEra:{state:true}};
  declare page:Page;declare menuOpen:boolean;declare theme:'light'|'dark';declare completed:string[];declare selectedDoc:DocItem;declare docHtml:string;declare selectedChallenge:TypeChallenge;declare draft:string;declare challengeResult:'idle'|'passed'|'failed';declare questionIndex:number;declare answers:Record<string,number>;declare assessmentDone:boolean;declare selectedVersion:TypeScriptVersion;declare versionEra:'Todas'|VersionEra;

  constructor(){super();this.page='dashboard';this.menuOpen=false;this.theme=(localStorage.getItem('typescript-academy.theme')as 'light'|'dark')??'dark';this.completed=this.restore(progressKey);this.selectedDoc=DOCUMENTS[0]!;this.docHtml='';this.selectedChallenge=CHALLENGES[0]!;this.draft=this.selectedChallenge.starter;this.challengeResult='idle';this.questionIndex=0;this.answers={};this.assessmentDone=false;this.selectedVersion=TYPE_SCRIPT_VERSIONS[0]!;this.versionEra='Todas';document.documentElement.dataset.theme=this.theme}
  override createRenderRoot(){return this}
  override connectedCallback(){super.connectedCallback();window.addEventListener('hashchange',this.readHash);this.readHash()}
  override disconnectedCallback(){window.removeEventListener('hashchange',this.readHash);super.disconnectedCallback()}
  override firstUpdated(){void this.loadDoc(this.selectedDoc)}
  private readonly readHash=()=>{const route=location.hash.replace('#/','')as Page;if(['dashboard','curriculum','documentation','versions','challenges','assessments','case-study'].includes(route))this.page=route||'dashboard'};
  private restore(key:string):string[]{try{return JSON.parse(localStorage.getItem(key)??'[]')}catch{return[]}}
  private navigate(page:Page){this.page=page;this.menuOpen=false;history.replaceState(null,'',`#/${page}`);window.scrollTo({top:0,behavior:'smooth'})}
  private toggleTheme(){this.theme=this.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=this.theme;localStorage.setItem('typescript-academy.theme',this.theme)}
  private finish(id:string){if(this.completed.includes(id))return;this.completed=[...this.completed,id];localStorage.setItem(progressKey,JSON.stringify(this.completed))}
  private async loadDoc(doc:DocItem){this.selectedDoc=doc;this.docHtml='<p>Carregando capítulo…</p>';try{const response=await fetch(doc.path);if(!response.ok)throw new Error();this.docHtml=marked.parse(await response.text(),{async:false})as string}catch{this.docHtml='<p>Não foi possível carregar este capítulo.</p>'}}
  private openChallenge(challenge:TypeChallenge){this.selectedChallenge=challenge;this.draft=challenge.starter;this.challengeResult='idle'}
  private validateChallenge(){const passed=this.selectedChallenge.solutionPattern.test(this.draft);this.challengeResult=passed?'passed':'failed';if(passed){const ids=this.restore(challengeKey);if(!ids.includes(this.selectedChallenge.id))localStorage.setItem(challengeKey,JSON.stringify([...ids,this.selectedChallenge.id]));this.finish(`challenge:${this.selectedChallenge.id}`)}}
  private choose(index:number){const question=QUESTIONS[this.questionIndex]!;this.answers={...this.answers,[question.id]:index}}
  private nextQuestion(){if(this.questionIndex===QUESTIONS.length-1){this.assessmentDone=true;const score=QUESTIONS.filter(item=>this.answers[item.id]===item.answer).length;localStorage.setItem('typescript-academy.assessment',JSON.stringify({score,total:QUESTIONS.length,date:new Date().toISOString()}));if(score>=7)this.finish('assessment')}else this.questionIndex+=1}
  private get progress(){return Math.min(Math.round(this.completed.length/(TRACKS.length+CHALLENGES.length+1)*100),100)}

  override render(){return html`<div class="academy-shell">
    <header class="academy-header"><button class="mobile-menu" @click=${()=>this.menuOpen=!this.menuOpen} aria-label="Abrir menu">☰</button><button class="academy-brand" @click=${()=>this.navigate('dashboard')}><academy-badge>TS</academy-badge><span><strong>TypeScript Academy</strong><small>DevForge Learning Lab</small></span></button><label class="academy-search"><span>⌕</span><input placeholder="Buscar tipos, generics e conceitos…" aria-label="Buscar na Academy"/><kbd>⌘ K</kbd></label><div class="header-actions"><button @click=${this.toggleTheme} aria-label="Alternar tema">${this.theme==='dark'?'☀':'◐'}</button><span>DF</span></div></header>
    <aside class=${`academy-sidebar ${this.menuOpen?'open':''}`}><div class="workspace-card"><academy-badge>TS</academy-badge><span><strong>TypeScript 7.0</strong><small>Compilador nativo · Lit 3</small></span><em>v7</em></div><div class="academy-progress"><header><span>Progresso geral</span><strong>${this.progress}%</strong></header><i><b style=${`width:${this.progress}%`}></b></i><small>${this.completed.length} evidências registradas</small></div>${this.navGroup('Início',[['dashboard','Visão geral','⌂','']])}${this.navGroup('Formação',[['curriculum','Trilha TypeScript','◇','12'],['documentation','Documentação','▤',String(DOCUMENTS.length)],['versions','Linha do tempo','↗',String(TYPE_SCRIPT_VERSIONS.length)]])}${this.navGroup('Praticar',[['challenges','Type Challenges','⌘',String(CHALLENGES.length)],['case-study','Estudo de caso','⇄','Lab']])}${this.navGroup('Avaliar',[['assessments','Testes técnicos','✓','3']])}<div class="sidebar-note"><span>AMBIENTE ACADÊMICO</span><strong>TypeScript-first</strong><p>Aprenda a modelar, provar e proteger contratos.</p></div></aside>
    <main class="academy-main">${this.renderPage()}</main>${this.menuOpen?html`<button class="menu-backdrop" @click=${()=>this.menuOpen=false} aria-label="Fechar menu"></button>`:nothing}
  </div>`}
  private navGroup(label:string,items:Array<[Page,string,string,string]>){return html`<nav><p>${label}</p>${items.map(([page,title,icon,badge])=>html`<button class=${this.page===page?'active':''} @click=${()=>this.navigate(page)}><i>${icon}</i><span>${title}</span>${badge?html`<em>${badge}</em>`:nothing}</button>`)}</nav>`}
  private renderPage(){switch(this.page){case'curriculum':return this.curriculum();case'documentation':return this.documentation();case'versions':return this.versions();case'challenges':return this.challenges();case'assessments':return this.assessments();case'case-study':return this.caseStudy();default:return this.dashboard()}}
  private dashboard(){const hours=TRACKS.reduce((sum,item)=>sum+item.hours,0);return html`<section class="academy-page"><div class="ts-hero"><div><span class="eyebrow">TYPESCRIPT LEARNING SYSTEM</span><h1>Pense em tipos.<br/><em>Projete contratos.</em></h1><p>Uma formação completa para dominar TypeScript do narrowing à arquitetura, com documentação, desafios e evidências reais.</p><div class="hero-tags"><span>TypeScript 7.0</span><span>Strict mode</span><span>Lit 3</span><span>Vitest</span></div><button @click=${()=>this.navigate('curriculum')}>Começar formação <b>→</b></button></div><aside><academy-badge>TS</academy-badge><small>PRÓXIMO PASSO</small><strong>Modelo mental e inferência</strong><span>Entenda o compilador antes das APIs.</span></aside></div><div class="academy-metrics">${this.metric('12','Módulos da trilha','Do fundamento à arquitetura','◇')}${this.metric(String(hours),'Horas guiadas','Teoria, prática e revisão','◷')}${this.metric(String(TYPE_SCRIPT_VERSIONS.length),'Marcos de versão','Do TypeScript 1.0 ao 7.0','↗')}${this.metric(String(DOCUMENTS.length),'Capítulos técnicos','Referência dentro da Academy','▤')}</div><section class="dashboard-section"><header><div><span class="eyebrow">APRENDER AGORA</span><h2>Escolha como evoluir hoje</h2></div><span>Conceito → prática → evidência</span></header><div class="action-grid">${this.action('Trilha completa','Siga os módulos em ordem e marque seu progresso.','curriculum','◇')}${this.action('Documentação','Consulte exemplos e decisões sem sair do Lab.','documentation','▤')}${this.action('Linha do tempo','Entenda mudanças, impactos e migrações do 1.0 ao 7.0.','versions','↗')}${this.action('Type Challenges','Resolva problemas de tipos do Júnior ao Sênior.','challenges','⌘')}${this.action('Teste técnico','Valide fundamentos, generics e arquitetura.','assessments','✓')}</div></section><div class="dashboard-lower"><article class="panel track-preview"><header><div><span class="eyebrow">MAPA DE DOMÍNIO</span><h2>Progressão por nível</h2></div><button @click=${()=>this.navigate('curriculum')}>Abrir trilha →</button></header>${(['Fundamentos','Intermediário','Avançado']as const).map((level,index)=>{const count=TRACKS.filter(item=>item.level===level).length;return html`<div><span><b>${index+1}</b><strong>${level}</strong><small>${count} módulos acadêmicos</small></span><i><b style=${`width:${[34,67,100][index]}%`}></b></i></div>`})}</article><article class="panel mental-model"><span>TS</span><small>MODELO MENTAL</small><h2>Tipos desaparecem no runtime</h2><p>TypeScript prova contratos durante o desenvolvimento. Dados externos continuam exigindo validação quando o JavaScript executa.</p><button @click=${()=>this.navigate('documentation')}>Estudar fronteiras →</button></article></div></section>`}
  private metric(value:string,label:string,detail:string,icon:string){return html`<article class="panel academy-metric"><span>${icon}</span><div><strong>${value}</strong><b>${label}</b><small>${detail}</small></div></article>`}
  private action(title:string,detail:string,page:Page,icon:string){return html`<button class="panel action-card" @click=${()=>this.navigate(page)}><span>${icon}</span><div><strong>${title}</strong><p>${detail}</p></div><b>→</b></button>`}
  private curriculum(){return html`<section class="academy-page"><header class="page-hero"><div><span class="eyebrow">CURRÍCULO TYPESCRIPT</span><h1>Da inferência à arquitetura.</h1><p>Doze módulos organizados por dependência conceitual, com objetivos e tópicos verificáveis.</p></div><aside><strong>${TRACKS.length}</strong><span>módulos</span><small>${TRACKS.reduce((s,t)=>s+t.hours,0)} horas guiadas</small></aside></header><div class="level-summary">${(['Fundamentos','Intermediário','Avançado']as const).map(level=>html`<span><i></i>${level}<b>${TRACKS.filter(item=>item.level===level).length}</b></span>`)}</div><div class="track-grid">${TRACKS.map(track=>html`<article class="panel track-card"><header><span>${String(track.order).padStart(2,'0')}</span><small>${track.level}</small></header><h2>${track.title}</h2><p>${track.description}</p><div>${track.topics.map(topic=>html`<em>${topic}</em>`)}</div><footer><span>◷ ${track.hours}h</span><button class=${this.completed.includes(track.id)?'done':''} @click=${()=>this.finish(track.id)}>${this.completed.includes(track.id)?'✓ Concluído':'Marcar concluído'}</button></footer></article>`)}</div></section>`}
  private documentation(){return html`<section class="academy-page"><header class="page-hero compact"><div><span class="eyebrow">KNOWLEDGE BASE</span><h1>Documentação TypeScript</h1><p>Conceitos, exemplos e decisões disponíveis dentro da Academy.</p></div><aside><strong>${DOCUMENTS.length}</strong><span>capítulos</span></aside></header><div class="academy-docs"><nav class="panel">${DOCUMENTS.map((doc,index)=>html`<button class=${this.selectedDoc.path===doc.path?'active':''} @click=${()=>void this.loadDoc(doc)}><span>${String(index+1).padStart(2,'0')}</span><div><strong>${doc.title}</strong><small>${doc.description}</small></div><b>→</b></button>`)}</nav><article class="panel doc-reader"><header><span class="eyebrow">CAPÍTULO SELECIONADO</span><h2>${this.selectedDoc.title}</h2><p>${this.selectedDoc.description}</p></header><div class="markdown-body">${unsafeHTML(this.docHtml)}</div></article></div></section>`}
  private versions(){const visible=this.versionEra==='Todas'?TYPE_SCRIPT_VERSIONS:TYPE_SCRIPT_VERSIONS.filter(item=>item.era===this.versionEra);const version=this.selectedVersion;return html`<section class="academy-page"><header class="page-hero compact version-hero"><div><span class="eyebrow">EVOLUÇÃO DA LINGUAGEM</span><h1>De tipos opcionais ao compilador nativo.</h1><p>Navegue pelos marcos do TypeScript, entenda o impacto real de cada release e prepare upgrades com segurança.</p></div><aside><strong>1.0 → 7.0</strong><span>12 anos de evolução</span><small>${TYPE_SCRIPT_VERSIONS.length} marcos estudados</small></aside></header><nav class="version-filters" aria-label="Filtrar linha do tempo">${VERSION_ERAS.map(era=>html`<button class=${this.versionEra===era?'active':''} @click=${()=>{this.versionEra=era;this.selectedVersion=(era==='Todas'?TYPE_SCRIPT_VERSIONS:TYPE_SCRIPT_VERSIONS.filter(item=>item.era===era))[0]!}}>${era}</button>`)}</nav><div class="version-layout"><div class="version-timeline">${visible.map(item=>html`<button class=${this.selectedVersion.version===item.version?'active':''} @click=${()=>this.selectedVersion=item}><span class="version-dot"></span><small>${item.released} · ${item.era}</small><strong>TypeScript ${item.version}</strong><p>${item.headline}</p></button>`)}</div><article class="panel version-detail"><header><div><span class="eyebrow">${version.era} · ${version.released}</span><h2>TypeScript ${version.version}</h2><p>${version.headline}</p></div><span class="version-number">${version.version}</span></header><p class="version-summary">${version.summary}</p><section><h3>O que mudou</h3><ul>${version.changes.map(change=>html`<li><span>✓</span>${change}</li>`)}</ul></section><aside><span>GUIA DE MIGRAÇÃO</span><p>${version.migration}</p></aside>${version.code?html`<div class="version-code"><header><span><i></i><i></i><i></i>migration.ts</span><button @click=${()=>void navigator.clipboard.writeText(version.code??'')}>Copiar</button></header><pre><code>${version.code}</code></pre></div>`:nothing}<footer><button @click=${()=>this.finish(`version:${version.version}`)}>${this.completed.includes(`version:${version.version}`)?'✓ Versão estudada':'Marcar como estudada'}</button><button @click=${()=>this.navigate('documentation')}>Abrir guia completo →</button></footer></article></div></section>`}
  private challenges(){const done=this.restore(challengeKey);return html`<section class="academy-page"><header class="page-hero compact"><div><span class="eyebrow">TYPE CHALLENGES</span><h1>Faça o compilador trabalhar.</h1><p>Modele relações, elimine estados inválidos e explique cada decisão.</p></div><aside><strong>${done.length}/${CHALLENGES.length}</strong><span>resolvidos</span></aside></header><div class="challenge-layout"><nav class="panel challenge-nav">${CHALLENGES.map((challenge,index)=>html`<button class=${this.selectedChallenge.id===challenge.id?'active':''} @click=${()=>this.openChallenge(challenge)}><span>${done.includes(challenge.id)?'✓':index+1}</span><div><small>${challenge.level}</small><strong>${challenge.title}</strong></div></button>`)}</nav><main><article class="panel challenge-brief"><span>${this.selectedChallenge.level}</span><h2>${this.selectedChallenge.title}</h2><p>${this.selectedChallenge.brief}</p><div>${this.selectedChallenge.skills.map(skill=>html`<em>${skill}</em>`)}</div></article><article class="code-workspace"><header><span><i></i><i></i><i></i>solution.ts</span><button @click=${()=>{this.draft=this.selectedChallenge.starter;this.challengeResult='idle'}}>Resetar</button></header><textarea .value=${this.draft} @input=${(event:InputEvent)=>{this.draft=(event.target as HTMLTextAreaElement).value;this.challengeResult='idle'}} spellcheck="false"></textarea><footer><span>${this.challengeResult==='failed'?this.selectedChallenge.hint:'O validador procura o conceito essencial da solução.'}</span><button @click=${this.validateChallenge}>Validar tipo</button></footer></article>${this.challengeResult!=='idle'?html`<div class=${`challenge-feedback ${this.challengeResult}`}><strong>${this.challengeResult==='passed'?'✓ Solução reconhecida':'× Ainda não'}</strong><span>${this.challengeResult==='passed'?'Evidência registrada. Explique por que o tipo preserva a relação.':this.selectedChallenge.hint}</span></div>`:nothing}</main></div></section>`}
  private assessments(){const current=QUESTIONS[this.questionIndex]!;const score=QUESTIONS.filter(item=>this.answers[item.id]===item.answer).length;return html`<section class="academy-page"><header class="page-hero compact"><div><span class="eyebrow">AVALIAÇÃO TÉCNICA</span><h1>Valide seu domínio TypeScript.</h1><p>Nove questões progressivas com explicação e corte de aprovação em 80%.</p></div><aside><strong>80%</strong><span>nota mínima</span></aside></header>${!this.assessmentDone?html`<article class="panel assessment-card"><header><span>Questão ${this.questionIndex+1} de ${QUESTIONS.length}</span><i><b style=${`width:${(this.questionIndex+1)/QUESTIONS.length*100}%`}></b></i><small>${current.level}</small></header><h2>${current.prompt}</h2><div>${current.options.map((option,index)=>html`<button class=${this.answers[current.id]===index?'selected':''} @click=${()=>this.choose(index)}><span>${'ABCD'[index]}</span>${option}<i>${this.answers[current.id]===index?'✓':''}</i></button>`)}</div><footer><button ?disabled=${this.answers[current.id]===undefined} @click=${this.nextQuestion}>${this.questionIndex===QUESTIONS.length-1?'Finalizar':'Próxima questão'} →</button></footer></article>`:html`<article class=${`panel assessment-result ${score>=7?'passed':''}`}><span>${score>=7?'✓':'↻'}</span><small>RESULTADO FINAL</small><h2>${Math.round(score/QUESTIONS.length*100)}%</h2><p>${score}/${QUESTIONS.length} respostas corretas · ${score>=7?'Avaliação aprovada':'Revise os módulos e tente novamente'}</p><div>${QUESTIONS.map(item=>html`<details><summary>${this.answers[item.id]===item.answer?'✓':'×'} ${item.level}</summary><p>${item.explanation}</p></details>`)}</div><button @click=${()=>{this.questionIndex=0;this.answers={};this.assessmentDone=false}}>Refazer avaliação</button></article>`}</section>`}
  private caseStudy(){return html`<section class="academy-page"><header class="page-hero"><div><span class="eyebrow">ESTUDO DE CASO</span><h1>Pipeline resiliente e tipado.</h1><p>O antigo Pulse Queue continua como aplicação prática de generics, composição, erros, filas e idempotência.</p></div><aside><strong>5</strong><span>contratos executáveis</span><small>Vitest · strict</small></aside></header><div class="case-grid"><article class="panel architecture-card"><header><span>Producer</span><b>→</b><span>Main Queue</span><b>→</b><span>Processor</span></header><div><span><i class="ok"></i>Processed</span><span><i class="warn"></i>Retry</span><span><i class="danger"></i>Dead-letter</span></div><pre><code>InMemoryQueue&lt;Message&lt;Order&gt;&gt;\nOrderProcessor.processNext(): Promise&lt;ProcessingResult&gt;</code></pre></article><article class="panel case-lessons"><span class="eyebrow">CONCEITOS APLICADOS</span><h2>O que investigar no código</h2>${['Generic preserva o payload da mensagem','Union descreve todos os resultados','Composição injeta filas e store','Readonly protege contratos','Testes provam idempotência e retry'].map((item,index)=>html`<p><span>${index+1}</span>${item}</p>`)}</article></div><article class="panel command-card"><div><strong>Execute o caso no terminal</strong><span>O cenário mínimo processa uma ordem e exibe o resultado.</span></div><code>npm run cli --workspace=@devforge/typescript</code></article></section>`}
}
customElements.define('typescript-academy',TypeScriptAcademy);
declare global{interface HTMLElementTagNameMap{'typescript-academy':TypeScriptAcademy}}
