export type VersionEra = 'Fundação' | 'Sistema de tipos' | 'TypeScript moderno' | 'Transição nativa';

export interface TypeScriptVersion {
  version: string;
  released: string;
  era: VersionEra;
  headline: string;
  summary: string;
  changes: string[];
  migration: string;
  code?: string;
}

export const VERSION_ERAS: Array<'Todas' | VersionEra> = ['Todas', 'Fundação', 'Sistema de tipos', 'TypeScript moderno', 'Transição nativa'];

export const TYPE_SCRIPT_VERSIONS: TypeScriptVersion[] = [
  {version:'7.0',released:'2026',era:'Transição nativa',headline:'Compilador e language service nativos',summary:'O compilador reescrito em Go substitui a base JavaScript e reduz drasticamente tempos de build e inicialização.',changes:['Compilador nativo distribuído pelo pacote principal','Language service nativo para editores','Compatibilidade de linha de comando com a transição iniciada no 6.0','Compiler API ainda não disponível nesta primeira versão'],migration:'Resolva primeiro os avisos do TypeScript 6.0, ative stableTypeOrdering durante a comparação e mantenha ferramentas que dependem da Compiler API no pacote TypeScript 6.',code:'npm install -D typescript@^7.0.0\n# execução paralela durante a migração\nnpx tsc\nnpx tsc6'},
  {version:'6.0',released:'2026',era:'Transição nativa',headline:'A ponte segura para o TypeScript 7',summary:'Última versão da base JavaScript, criada para explicitar defaults modernos e preparar projetos para o compilador nativo.',changes:['strict, module esnext e target es2025 tornam-se defaults','noUncheckedSideEffectImports habilitado por padrão','Suporte a ES2025 e tipos de Temporal','Depreciações antigas passam a emitir avisos de migração'],migration:'Atualize primeiro para 6.0, declare opções antes implícitas no tsconfig e remova moduleResolution node10 e formatos AMD, UMD ou SystemJS.',code:'{\n  "compilerOptions": {\n    "strict": true,\n    "target": "ES2025",\n    "module": "ESNext",\n    "stableTypeOrdering": true\n  }\n}'},
  {version:'5.9',released:'2025',era:'TypeScript moderno',headline:'Imports adiados e Node.js estável',summary:'Refina módulos, experiência do editor e desempenho antes da grande transição do compilador.',changes:['Sintaxe import defer','Opção module node20 estável','Preview de hovers expansíveis','Melhorias de inferência e menos instanciações de tipos'],migration:'Revise bundlers antes de adotar import defer e prefira node20 quando o contrato de runtime for estável.',code:'import defer * as analytics from "./analytics.js";\n\nanalytics.track("lesson_started");'},
  {version:'5.8',released:'2025',era:'TypeScript moderno',headline:'Retornos condicionais e módulos Node.js',summary:'Aprimora a análise de funções genéricas condicionais e a interoperabilidade entre CommonJS e ESM.',changes:['Checagem granular de retornos condicionais','require() de módulos ESM sob nodenext','Opção module node18','Melhorias em branches e performance'],migration:'Teste novamente funções com retorno condicional e valide a estratégia ESM/CJS do package.'},
  {version:'5.7',released:'2024',era:'TypeScript moderno',headline:'Extensões reescritas e projetos mais seguros',summary:'Melhora a execução direta de TypeScript e a consistência de imports em projetos compostos.',changes:['rewriteRelativeImportExtensions','Detecção de variáveis nunca inicializadas','Busca de tsconfig em projetos compostos','Melhorias de desempenho'],migration:'Use rewriteRelativeImportExtensions apenas quando seu runtime aceita os arquivos emitidos e audite imports relativos.'},
  {version:'5.6',released:'2024',era:'TypeScript moderno',headline:'Erros prováveis e iteradores mais precisos',summary:'Detecta condições sempre verdadeiras ou nulas e endurece a análise de imports e iteradores.',changes:['Erros para checagens truthy/nullish suspeitas','IteratorObject e tipos de helpers de iterator','noUncheckedSideEffectImports','Opção noCheck para separar emissão e análise'],migration:'Corrija expressões condicionais suspeitas e declare módulos de assets ao habilitar noUncheckedSideEffectImports.'},
  {version:'5.5',released:'2024',era:'TypeScript moderno',headline:'Predicados inferidos',summary:'O compilador passa a inferir type predicates em filtros comuns e introduz contratos para emissão isolada.',changes:['Inferência de type predicates','Control-flow narrowing para acessos indexados constantes','isolatedDeclarations','Regex com checagem de sintaxe básica'],migration:'Remova predicates manuais apenas quando a inferência preservar a API pública e teste declarations isoladas em bibliotecas.'},
  {version:'5.4',released:'2024',era:'TypeScript moderno',headline:'Controle explícito de inferência',summary:'NoInfer permite escolher quais posições participam da inferência de um generic.',changes:['Utility type NoInfer','Narrowing preservado em closures','Tipos para Object.groupBy e Map.groupBy'],migration:'Substitua truques auxiliares por NoInfer com testes de tipo que provem chamadas válidas e inválidas.',code:'function choose<C extends string>(options: C[], initial?: NoInfer<C>) {}'},
  {version:'5.2',released:'2023',era:'TypeScript moderno',headline:'Recursos descartáveis e metadata',summary:'Adiciona gerenciamento determinístico de recursos e melhora decorators e operações sobre unions de arrays.',changes:['using e await using','Symbol.dispose e Symbol.asyncDispose','Decorator metadata','Métodos de arrays em unions mais fáceis de usar'],migration:'Garanta suporte do runtime ou polyfill para symbols de descarte antes de usar using.'},
  {version:'5.0',released:'2023',era:'TypeScript moderno',headline:'Decorators padronizados',summary:'Um grande marco de linguagem com decorators alinhados ao JavaScript e inferência literal controlável.',changes:['Decorators do padrão ECMAScript','const type parameters','verbatimModuleSyntax','Múltiplos extends em tsconfig'],migration:'Decorators legados e decorators padrão têm contratos diferentes; migre conscientemente e revise metadata.'},
  {version:'4.9',released:'2022',era:'TypeScript moderno',headline:'Validação sem perder inferência',summary:'O operador satisfies verifica um contrato preservando os tipos específicos da expressão.',changes:['Operador satisfies','Narrowing com operador in','Auto-accessors em classes','Melhorias em file watching'],migration:'Prefira satisfies a casts quando precisa validar configuração sem alargar literais.',code:'const routes = { home: "/" } satisfies Record<string, `/${string}`>;' },
  {version:'4.5',released:'2021',era:'Sistema de tipos',headline:'Awaited e módulos ES2022',summary:'Modela melhor valores assíncronos e dá mais controle sobre bibliotecas e resolução de módulos.',changes:['Utility type Awaited','module es2022','Tail-recursion elimination em conditional types','Imports preservados por tipo'],migration:'Troque helpers próprios de Promise por Awaited e monitore tipos recursivos que antes atingiam limites.'},
  {version:'4.1',released:'2020',era:'Sistema de tipos',headline:'Tipos que manipulam strings',summary:'Template literal types e remapeamento de chaves tornam transformações de API muito mais expressivas.',changes:['Template literal types','Key remapping em mapped types','Conditional types recursivos','noUncheckedIndexedAccess'],migration:'Habilite noUncheckedIndexedAccess em etapas: índices passam a incluir undefined.',code:'type EventName<T extends string> = `${T}Changed`;' },
  {version:'4.0',released:'2020',era:'Sistema de tipos',headline:'Tuplas variádicas',summary:'Assinaturas de funções compostas deixam de exigir dezenas de overloads.',changes:['Variadic tuple types','Labeled tuple elements','unknown em catch opt-in','Class property inference'],migration:'Simplifique overloads repetitivos e nomeie elementos de tupla para melhorar a leitura no editor.'},
  {version:'3.7',released:'2019',era:'Sistema de tipos',headline:'Optional chaining chega ao TypeScript',summary:'Operadores modernos reduzem verificações ruidosas, junto com assertion functions e recursive aliases.',changes:['Optional chaining','Nullish coalescing','Assertion functions','Aliases de tipo recursivos'],migration:'Não substitua || por ?? mecanicamente: zero, false e string vazia têm semânticas diferentes.'},
  {version:'3.0',released:'2018',era:'Sistema de tipos',headline:'unknown e project references',summary:'Surge a alternativa segura a any e uma base escalável para builds de monorepos.',changes:['Tipo unknown','Project references','Tuplas em parâmetros rest e spread','defaultProps para JSX'],migration:'Use unknown em fronteiras não confiáveis e divida builds grandes com composite e references.'},
  {version:'2.8',released:'2018',era:'Sistema de tipos',headline:'Conditional types e infer',summary:'O sistema de tipos passa a expressar transformações dependentes de condições.',changes:['Conditional types','Palavra-chave infer','Utility types Exclude, Extract, NonNullable e ReturnType','Controle granular em mapped modifiers'],migration:'Evite conditional types excessivamente distribuídos; envolva o parâmetro em tupla quando não quiser distribuição.'},
  {version:'2.1',released:'2016',era:'Sistema de tipos',headline:'keyof e mapped types',summary:'Tipos podem ser derivados sistematicamente de outros tipos, reduzindo contratos duplicados.',changes:['Operador keyof','Indexed access types','Mapped types','Object spread e rest'],migration:'Substitua listas de chaves duplicadas por keyof e derive variações com mapped types.'},
  {version:'2.0',released:'2016',era:'Sistema de tipos',headline:'Null safety e análise de fluxo',summary:'strictNullChecks muda a forma de modelar ausência e o controle de fluxo passa a refinar tipos.',changes:['strictNullChecks','Control-flow based type analysis','Tipo never','Discriminated unions'],migration:'Ative strictNullChecks por módulo e modele estados ausentes explicitamente antes de avançar para strict completo.'},
  {version:'1.6',released:'2015',era:'Fundação',headline:'JSX e interseções',summary:'TypeScript se aproxima do desenvolvimento moderno de interfaces e composição estrutural.',changes:['Suporte a JSX','Intersection types','Classes abstratas','Guards definidos pelo usuário'],migration:'Use extensão .tsx para JSX e mantenha guards pequenos, previsíveis e testáveis.'},
  {version:'1.4',released:'2015',era:'Fundação',headline:'Union types',summary:'Valores alternativos ganham representação explícita sem abandonar segurança.',changes:['Union types','Aliases de tipo','const enums','Melhor inferência de chamadas'],migration:'Substitua any usado para alternativas conhecidas por unions e faça narrowing antes de operar.'},
  {version:'1.0',released:'2014',era:'Fundação',headline:'A linguagem se torna estável',summary:'A primeira versão estável consolida JavaScript tipado, interfaces, classes e tooling orientado a editores.',changes:['Primeira versão estável','Tipagem estrutural','Interfaces e classes','Emissão para JavaScript'],migration:'Marco histórico: projetos atuais devem usar strict e módulos modernos, não configurações compatíveis com 1.x.'}
];
