import { Seniority } from '../technical-assessments/technical-assessment-bank';

export interface TechnicalAnswer { id:string; question:string; answer:string; category:string; level:Seniority; points:string[]; }

export const TECHNICAL_QA: TechnicalAnswer[] = [
  {id:'qa-1',question:'Como funciona a change detection com OnPush?',answer:'OnPush reduz as verificações do subtree. O componente volta a ser verificado quando recebe nova referência por input, trata um evento, um signal lido no template muda ou uma fonte observada pelo AsyncPipe emite.',category:'Rendering',level:'Júnior',points:['Trate inputs como imutáveis','Signals notificam consumidores','OnPush não significa renderizar apenas uma vez']},
  {id:'qa-2',question:'Quando usar Signals e quando usar RxJS?',answer:'Signals modelam estado síncrono e derivado da interface. RxJS modela eventos e fluxos assíncronos ao longo do tempo. Use interoperabilidade perto do consumidor, sem converter repetidamente.',category:'Reatividade',level:'Pleno',points:['Signal para leitura atual','RxJS para tempo, cancelamento e composição','computed para derivação']},
  {id:'qa-3',question:'Qual a diferença entre providers root, route e component?',answer:'O injector raiz compartilha uma instância na aplicação. A rota cria escopo para a feature lazy. O componente cria uma instância por subtree, alinhando estado e ciclo de vida àquela UI.',category:'DI',level:'Pleno',points:['Escopo define compartilhamento','Escopo define lifecycle','Estado de feature raramente precisa ser global']},
  {id:'qa-4',question:'Por que um route guard não é segurança?',answer:'O código cliente está sob controle do usuário e pode ser contornado. Guards melhoram navegação e UX; autorização verdadeira precisa ser validada pelo servidor em cada operação protegida.',category:'Segurança',level:'Júnior',points:['Cliente não é fronteira de confiança','Backend valida permissão','Guard ainda é útil para UX']},
  {id:'qa-5',question:'switchMap, concatMap, mergeMap ou exhaustMap?',answer:'switchMap mantém o fluxo mais recente; concatMap preserva ordem em fila; mergeMap executa concorrentemente; exhaustMap ignora novos eventos enquanto o atual não termina.',category:'RxJS',level:'Pleno',points:['Busca: switchMap','Fila de escrita: concatMap','Submit protegido: exhaustMap']},
  {id:'qa-6',question:'Como evitar memory leaks em Angular?',answer:'Prefira AsyncPipe e recursos vinculados ao template. Para código imperativo, use takeUntilDestroyed com DestroyRef e encerre timers, observers, sockets e bibliotecas externas.',category:'Qualidade',level:'Júnior',points:['Lifecycle explícito','Cleanup idempotente','Não assine só para copiar estado']},
  {id:'qa-7',question:'Quando uma facade agrega valor?',answer:'Quando estabiliza um contrato usado por múltiplos consumidores, coordena fontes ou protege a UI de detalhes voláteis. Uma camada que apenas renomeia métodos aumenta cerimônia.',category:'Arquitetura',level:'Sênior',points:['Contrato estável','Orquestração real','Evitar abstração prematura']},
  {id:'qa-8',question:'Como decidir entre CSR, SSR e prerender?',answer:'Use requisitos de SEO, primeira resposta, personalização, frequência de mudança, cache e custo operacional. Prerender atende páginas estáticas; SSR atende HTML por request; CSR favorece experiências privadas e interativas.',category:'Rendering',level:'Sênior',points:['Decisão mensurável','Hydration tem custo','Estratégias podem coexistir']},
  {id:'qa-9',question:'O que torna um formulário Angular robusto?',answer:'Modelo tipado, validação alinhada ao domínio, mensagens acessíveis, estados pending/disabled explícitos, prevenção de duplo envio e mapping entre formulário e contrato externo.',category:'Forms',level:'Pleno',points:['NonNullableFormBuilder','Erros ligados ao campo','DTO não vaza para a view']},
  {id:'qa-10',question:'Como estruturar uma feature Angular?',answer:'Agrupe por capacidade de negócio e mantenha UI, estado, data access e rotas próximos. Dependências apontam para contratos estáveis; componentes não acessam detalhes HTTP diretamente.',category:'Arquitetura',level:'Pleno',points:['Coesão por feature','Boundaries explícitos','Lazy loading por contexto']},
  {id:'qa-11',question:'Como testar sem acoplar ao markup?',answer:'Teste comportamento observável por papel, texto, interação e contrato público. Use Harnesses para componentes complexos, HttpTestingController para rede e RouterTestingHarness para navegação.',category:'Testes',level:'Pleno',points:['Evite detalhes privados','Teste DOM quando o usuário observa DOM','Poucos E2E de alto valor']},
  {id:'qa-12',question:'Quais sinais indicam problemas de performance?',answer:'Long tasks, bundle inicial crescente, renderizações repetidas, listas sem track, imagens pesadas e waterfalls de rede. Meça antes de otimizar e estabeleça budgets verificáveis.',category:'Performance',level:'Sênior',points:['DevTools e Web Vitals','Lazy e defer com intenção','Performance é requisito contínuo']},
];
