export interface AngularDocVersion {version:string;released:string;status:string;headline:string;summary:string;changes:string[];migration:string;example:string}
export const ANGULAR_DOC_VERSIONS:AngularDocVersion[]=[
{version:'20',released:'2025',status:'Atual no Lab',headline:'Reatividade moderna e APIs estáveis',summary:'O Lab usa Angular 20 e prioriza standalone APIs, signals e rendering moderno com contratos TypeScript estritos.',changes:['Signals fundamentais estabilizados','Melhorias em template type checking e diagnóstico','Evolução de SSR, hydration e experiência zoneless'],migration:'Atualize com ng update, valide a matriz Node/TypeScript/RxJS e resolva depreciações antes de ativar estratégias zoneless.',example:`@Component({\n  standalone: true,\n  template: \`<strong>{{ total() }}</strong>\`\n})\nexport class Cart {\n  items = signal<Item[]>([]);\n  total = computed(() => this.items().reduce((sum, item) => sum + item.price, 0));\n}`},
{version:'19',released:'2024',status:'Anterior',headline:'Standalone por padrão e reatividade expandida',summary:'Componentes passam a ser standalone por padrão e novas primitives aproximam estado assíncrono do modelo de signals.',changes:['Standalone como default','linkedSignal e resource em evolução','Incremental hydration e event replay'],migration:'Remova standalone:false apenas quando o componente realmente deixar o NgModule e revise bootstrap, providers e testes.',example:`const userId = signal('42');\nconst user = resource({\n  request: () => userId(),\n  loader: ({ request }) => fetchUser(request)\n});`},
{version:'18',released:'2024',status:'Anterior',headline:'Zoneless e controle de fluxo maduros',summary:'A transição para aplicações sem Zone.js começa, enquanto o novo template syntax e defer avançam.',changes:['Zoneless experimental','Novo control flow estabilizado','Event replay e melhorias de hydration'],migration:'Meça dependências de Zone.js e converta estado para signals ou notificações explícitas antes de testar zoneless.',example:`@if (user()) {\n  <app-profile [user]="user()!" />\n} @else {\n  <app-skeleton />\n}`},
{version:'17',released:'2023',status:'Anterior',headline:'Control flow e carregamento adiável',summary:'Templates recebem sintaxe embutida e blocos defer tornam performance uma decisão declarativa.',changes:['@if, @for e @switch','@defer com triggers','Novo application builder com Vite e esbuild'],migration:'Use a migration oficial para control flow e defina placeholder, loading e error ao adotar @defer.',example:`@defer (on viewport) {\n  <app-analytics />\n} @placeholder {\n  <app-chart-skeleton />\n}`},
{version:'16',released:'2023',status:'Legada',headline:'Signals e hydration chegam ao framework',summary:'A base da reatividade moderna surge junto de inputs obrigatórios e interoperabilidade aprimorada.',changes:['Signals em developer preview','Hydration não destrutiva','Required inputs e DestroyRef'],migration:'Introduza signals em estado local primeiro e mantenha a interoperabilidade com RxJS explícita nas fronteiras assíncronas.',example:`readonly count = signal(0);\nreadonly doubled = computed(() => this.count() * 2);`},
{version:'15',released:'2022',status:'Legada',headline:'Standalone APIs estáveis',summary:'Componentes, diretivas e pipes standalone deixam de ser experimentais e simplificam bootstrap e rotas.',changes:['Standalone APIs estáveis','provideRouter e provideHttpClient','Directive composition API'],migration:'Migre por feature; NgModules podem coexistir enquanto rotas e providers adotam as funções standalone.',example:`bootstrapApplication(AppComponent, {\n  providers: [provideRouter(routes), provideHttpClient()]\n});`},
{version:'14',released:'2022',status:'Legada',headline:'Formulários estritamente tipados',summary:'Reactive Forms ganham tipos seguros e standalone components aparecem como developer preview.',changes:['Typed Reactive Forms','Standalone components em preview','Função inject e melhor template diagnostics'],migration:'Revise formulários que dependiam de any e use NonNullableFormBuilder quando null não fizer parte do domínio.',example:`const form = new FormGroup({\n  email: new FormControl('', { nonNullable: true })\n});`}
];
