export interface FinalQuestion { id:string; area:string; level:'Júnior'|'Pleno'|'Sênior'; prompt:string; options:string[]; answer:number; explanation:string; }
export const FINAL_QUESTIONS:FinalQuestion[]=[
{id:'signals',area:'Reatividade',level:'Júnior',prompt:'Qual estado deve ser modelado com computed?',options:['Um valor recebido da API','Um valor derivado de outros signals','Um evento de clique','Uma conexão WebSocket'],answer:1,explanation:'computed representa estado derivado e evita sincronização manual.'},
{id:'di',area:'Arquitetura',level:'Júnior',prompt:'Qual opção mantém um serviço tree-shakable e disponível globalmente?',options:["@Injectable({ providedIn: 'root' })",'Provider em cada componente','Instância criada com new','Variável global'],answer:0,explanation:'providedIn root permite que o compilador remova serviços não usados.'},
{id:'template',area:'Templates',level:'Júnior',prompt:'Por que usar track em um bloco @for?',options:['Para validar formulários','Para identificar itens e minimizar operações no DOM','Para ativar OnPush','Para ordenar automaticamente'],answer:1,explanation:'track fornece identidade estável para reconciliar a coleção.'},
{id:'rx-concurrency',area:'RxJS',level:'Pleno',prompt:'Uma busca deve cancelar o request anterior quando o termo muda. Qual operador?',options:['concatMap','mergeMap','switchMap','exhaustMap'],answer:2,explanation:'switchMap troca para o fluxo mais recente e cancela a assinatura anterior.'},
{id:'forms',area:'Forms',level:'Pleno',prompt:'Onde deve ficar uma regra que compara dois campos do mesmo formulário?',options:['No template','Em cada FormControl isoladamente','Em um validator do FormGroup','Em um interceptor'],answer:2,explanation:'Validações cruzadas pertencem ao ancestral comum dos controles.'},
{id:'http',area:'HTTP',level:'Pleno',prompt:'Qual é a melhor responsabilidade para um interceptor?',options:['Renderizar mensagens','Adicionar preocupação transversal como autenticação','Armazenar todo estado da aplicação','Navegar entre páginas'],answer:1,explanation:'Interceptors tratam aspectos transversais do transporte.'},
{id:'testing',area:'Testes',level:'Pleno',prompt:'Um teste de componente resiliente deve priorizar:',options:['Métodos privados','Estrutura interna exata','Comportamento observável no DOM','Quantidade de detectChanges'],answer:2,explanation:'Testes por contrato permitem refatorar a implementação.'},
{id:'state',area:'Estado',level:'Sênior',prompt:'Qual sinal indica ownership de estado mal definido?',options:['computed sem setter','Mesmo dado mutável em vários stores','Um facade por boundary','DTO transformado no repository'],answer:1,explanation:'Múltiplas fontes graváveis produzem divergência e sincronização acidental.'},
{id:'ssr',area:'Rendering',level:'Sênior',prompt:'Qual cuidado é essencial em código executado com SSR?',options:['Sempre acessar window','Assumir DOM disponível','Isolar APIs do navegador e considerar o ambiente','Desativar hydration'],answer:2,explanation:'O servidor não oferece APIs do navegador; dependências precisam respeitar a plataforma.'},
{id:'performance',area:'Performance',level:'Sênior',prompt:'Qual é o primeiro passo de uma otimização responsável?',options:['Adicionar memoização em tudo','Trocar RxJS por Signals','Medir e localizar o gargalo','Desativar change detection'],answer:2,explanation:'Otimização sem medição aumenta complexidade sem provar benefício.'},
{id:'security',area:'Segurança',level:'Sênior',prompt:'Sobre bypassSecurityTrustHtml, qual afirmação é correta?',options:['É seguro para qualquer HTML externo','Deve ser usado somente após estabelecer uma fronteira de confiança','Substitui CSP','Sanitiza automaticamente o valor'],answer:1,explanation:'Bypass remove proteções; só cabe quando a confiança foi validada fora dessa API.'},
{id:'architecture',area:'Arquitetura',level:'Sênior',prompt:'Qual boundary reduz acoplamento entre UI e transporte?',options:['Componente importando HttpClient diretamente em toda tela','Repository/facade com contrato orientado ao domínio','SharedModule com todos os serviços','Objeto global de configuração mutável'],answer:1,explanation:'Repository e facade escondem DTOs, transporte e políticas da camada visual.'},
];
export const FINAL_PASS_RATIO=.8;
