import {ChangeDetectionStrategy,Component,computed,inject,signal} from '@angular/core';
import {MatIconModule} from '@angular/material/icon';
import {LearningProgressService} from '../../core/services/learning-progress.service';
import {CAPSTONE_TASK_COUNT} from '../capstone-project/capstone-project.data';
import {SANDBOX_CHALLENGES} from '../angular-sandbox/sandbox-challenges';
import {E2E_MISSIONS} from '../e2e-quality/e2e-missions';
import {FINAL_PASS_RATIO,FINAL_QUESTIONS} from './final-assessment.data';
interface FinalResult{score:number;total:number;date:string;answers:Record<string,number>}
const RESULT_KEY='angular-learning-lab.final-assessment';
@Component({selector:'app-final-certification',imports:[MatIconModule],templateUrl:'./final-certification.html',styleUrl:'./final-certification.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class FinalCertification{
 private readonly progressService=inject(LearningProgressService);
 readonly questions=FINAL_QUESTIONS;readonly active=signal(0);readonly answers=signal<Record<string,number>>({});readonly started=signal(false);readonly result=signal<FinalResult|null>(this.restoreResult());readonly studentName=signal(localStorage.getItem('angular-learning-lab.student-name')??'');
 readonly selectedAnswer=computed(()=>this.answers()[this.questions[this.active()].id]);readonly scorePercent=computed(()=>this.result()?Math.round(this.result()!.score/this.result()!.total*100):0);readonly passed=computed(()=>this.scorePercent()>=FINAL_PASS_RATIO*100);
 readonly gates=computed(()=>[{id:'path',label:'Trilha Angular',detail:`${this.progressService.completedModules().length}/${this.progressService.totalModules} módulos`,done:this.progressService.completedModules().length===this.progressService.totalModules,route:'/learning'},{id:'exams',label:'Provas temáticas',detail:`${this.progressService.passedExams()}/${this.progressService.totalExams} aprovadas`,done:this.progressService.passedExams()===this.progressService.totalExams,route:'/assessments'},{id:'capstone',label:'Projeto Final',detail:`${this.count('angular-capstone-progress')}/${CAPSTONE_TASK_COUNT} evidências`,done:this.count('angular-capstone-progress')===CAPSTONE_TASK_COUNT,route:'/capstone'},{id:'sandbox',label:'Angular Sandbox',detail:`${this.count('angular-learning-lab.sandbox.completed')}/${SANDBOX_CHALLENGES.length} workspaces`,done:this.count('angular-learning-lab.sandbox.completed')===SANDBOX_CHALLENGES.length,route:'/sandbox'},{id:'e2e',label:'E2E & Quality',detail:`${this.count('angular-learning-lab.e2e-quality')}/${E2E_MISSIONS.length} missões`,done:this.count('angular-learning-lab.e2e-quality')===E2E_MISSIONS.length,route:'/e2e-quality'},{id:'final',label:'Avaliação final',detail:this.result()?`${this.scorePercent()}% de acerto`:'não realizada',done:this.passed(),route:'/certification'}]);
 readonly completedGates=computed(()=>this.gates().filter(g=>g.done).length);readonly readiness=computed(()=>Math.round(this.completedGates()/this.gates().length*100));readonly certified=computed(()=>this.gates().every(g=>g.done)&&this.studentName().trim().length>=3);readonly certificateId=computed(()=>{const base=`${this.studentName().trim().toUpperCase()}|${this.result()?.date??''}|ANGULAR20`;let hash=0;for(const char of base)hash=((hash<<5)-hash+char.charCodeAt(0))|0;return `DF-ANG-${Math.abs(hash).toString(16).toUpperCase().padStart(8,'0')}`});
 select(index:number):void{this.answers.update(a=>({...a,[this.questions[this.active()].id]:index}))}previous():void{if(this.active()>0)this.active.update(i=>i-1)}next():void{if(this.active()<this.questions.length-1)this.active.update(i=>i+1);else this.finish()}finish():void{const score=this.questions.filter(q=>this.answers()[q.id]===q.answer).length;const result={score,total:this.questions.length,date:new Date().toISOString(),answers:this.answers()};this.result.set(result);localStorage.setItem(RESULT_KEY,JSON.stringify(result))}retry():void{this.answers.set({});this.active.set(0);this.result.set(null);this.started.set(true)}saveName(value:string):void{this.studentName.set(value);localStorage.setItem('angular-learning-lab.student-name',value)}print():void{window.print()}
 private count(key:string):number{try{const value=JSON.parse(localStorage.getItem(key)??'[]');return Array.isArray(value)?value.length:0}catch{return 0}}private restoreResult():FinalResult|null{try{return JSON.parse(localStorage.getItem(RESULT_KEY)??'null')}catch{return null}}
}
