import { ArrowRight, BookOpen, Boxes, BrainCircuit, CheckCircle2, Code2, Component, FlaskConical, GraduationCap, Layers3, Play, TestTube2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { DOCUMENTATION_CHAPTERS } from './documentation-chapters';

const modules=[{title:'Fundamentos e composição',skills:'JSX · props · children',progress:72,color:'violet'},{title:'Estado e hooks',skills:'state · effects · refs',progress:48,color:'cyan'},{title:'Dados e servidor',skills:'Router · Query · cache',progress:28,color:'green'},{title:'Qualidade e arquitetura',skills:'RTL · boundaries · performance',progress:12,color:'amber'}];
const tools=[{to:'/learning',label:'Trilha React',detail:'Aprenda em sequência com critérios claros.',icon:GraduationCap},{to:'/documentation',label:'Documentação',detail:'Consulte conceitos, APIs e decisões.',icon:BookOpen},{to:'/curriculum',label:'Mapa React',detail:'Explore as quinze áreas de domínio.',icon:Layers3},{to:'/tickets',label:'Estudo de caso',detail:'Investigue uma aplicação React real.',icon:FlaskConical},{to:'/analytics',label:'Componentes reais',detail:'Explore composição e visualização.',icon:Boxes}];

export function DashboardPage(){return <section className="page react-dashboard"><header className="react-hero"><div><span className="eyebrow"><Code2/> React Learning Lab</span><h1>Domine React construindo modelos mentais sólidos.</h1><p>Uma formação prática do primeiro componente à arquitetura de aplicações modernas, com exemplos reais, exercícios e validação de conhecimento.</p><div className="react-hero__meta"><span><Layers3/>5 módulos</span><span><Component/>React 19</span><span><TestTube2/>Vitest + RTL</span></div><Link className="primary-button" to="/learning"><Play/>Continuar formação</Link></div><aside><span className="react-orbit"><i><Code2/></i></span><div><small>PRÓXIMO MÓDULO</small><strong>Fundamentos e composição</strong><span>Componentes, JSX e fluxo de dados</span></div></aside></header>
<div className="academy-stats"><article className="panel"><span><GraduationCap/></span><div><strong>5</strong><small>Módulos da trilha</small><em>Do fundamento ao avançado</em></div></article><article className="panel"><span><BookOpen/></span><div><strong>{DOCUMENTATION_CHAPTERS.length}</strong><small>Capítulos técnicos</small><em>Leitura dentro da plataforma</em></div></article><article className="panel"><span><FlaskConical/></span><div><strong>1</strong><small>Estudo de caso</small><em>Aplicação React funcional</em></div></article><article className="panel"><span><CheckCircle2/></span><div><strong>6</strong><small>Testes automatizados</small><em>Contratos executáveis</em></div></article></div>
<section className="study-tools"><header><div><span className="eyebrow">Estudar agora</span><h2>Escolha como você quer evoluir hoje</h2></div><span>Teoria, prática e investigação</span></header><div>{tools.map(tool=><Link className="panel" to={tool.to} key={tool.label}><span><tool.icon/></span><div><strong>{tool.label}</strong><p>{tool.detail}</p></div><ArrowRight/></Link>)}</div></section>
<div className="academy-grid"><article className="panel curriculum-progress"><header><div><span className="eyebrow">Mapa de domínio</span><h2>Progresso por área</h2></div><Link to="/learning">Abrir trilha <ArrowRight/></Link></header><div>{modules.map(module=><div key={module.title}><header><span><strong>{module.title}</strong><small>{module.skills}</small></span><b>{module.progress}%</b></header><i><b className={module.color} style={{width:`${module.progress}%`}}/></i></div>)}</div></article><article className="panel learning-principles"><span><BrainCircuit/></span><small>MODELO MENTAL</small><h2>Render é uma fotografia</h2><p>Cada render captura props e estado daquele momento. Eventos e effects enxergam o snapshot ao qual pertencem.</p><div><span>01</span><p><strong>Renderize</strong> a partir do estado</p></div><div><span>02</span><p><strong>Derive</strong> em vez de sincronizar</p></div><div><span>03</span><p><strong>Use effects</strong> só para sistemas externos</p></div><Link to="/documentation">Estudar fundamentos <ArrowRight/></Link></article></div>
</section>}
